apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: myapp-namespace
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%  
  replicas: 4 
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: gerops/mytestrepo:e9cc92bdb524651be4705430ff5de1aa81559bb1
        ports:
        - containerPort: 8080
        resources: 
          requests:
            cpu: 100m
            memory: 250Mi
          limits: 
            cpu: 100m
            memory: 250Mi
        startupProbe:
          tcpSocket:
            port: 8181
          initialDelaySeconds: 20
          periodSeconds: 5
