apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: myapp-namespace
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%  
  replicas: 4 
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: gerops/mytestrepo:39032d42e164c9ee46e18b19e13fab9678a062d7
        ports:
        - containerPort: 8080
        resources: 
          requests:
            cpu: 100m
            memory: 250Mi
          limits: 
            cpu: 100m
            memory: 250Mi
