apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: app-repo-ir
  namespace: flux-system
spec:
  image: gerops/mytestrepo
  registry: docker.io
  policy:
    semver: ">=0.0.0"
  annotations:
    fluxcd.io/automated: "true"
