name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authorizatoin with config file
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods

      - name: Deploy to Production
        run: |
          SHA="${{ github.sha }}"
          echo "Using SHA: $SHA"  # Debug statement

          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mytestrepo:$SHA
          # Add your deployment steps here
          # Example: Run the specific version of the Docker image on your production environment
          # Assuming kubectl is configured, apply your Kubernetes deployment manifest to the specified namespace
          kubectl apply -f k8s/deployment.yaml
          # Add any additional deployment steps specific to your environment

