name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Deploy to Production
        run: |
          VERSION="${{ needs.build-and-push.outputs.version }}"
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mytestrepo:$VERSION

          # Add your deployment steps here
          # Example: Run the specific version of the Docker image on your production environment
          docker run -d -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/mytestrepo:$VERSION

